services:
  app:
    build: .
    container_name: leaflang-app
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET=clappy
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=leaflang_db
      - IP=0.0.0.0
    depends_on:
      - db
    command: ["./leaflang"]
    volumes:
      - ./static/user-images:/app/static/user-images


  db:
    image: postgres:15
    container_name: leaflang_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: leaflang_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sqlbackup.sql:/docker-entrypoint-initdb.d/sqlbackup.sql
volumes:
  pgdata:
