server:
  port: 8080

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format-sql: true
      show-sql: true
    main:
      web-development-type: servlet